export enum Injections {
  USER_REPOSITORY = 'UserRepository',
  VERIFICATION_TOKEN_REPOSITORY = 'VerificationTokenRepository',
  ENCRYPT_PORT = 'EncryptPort',
  JWT_PORT = 'JwtPort',
  EMAIL_PROVIDER = 'EmailProvider',
  USER_SERVICE = 'USER_SERVICE',
  CATEGORY_REPOSITORY = 'CategoryRepository',
  TRANSACTION_REPOSITORY = 'TransactionRepository',
  OFX_STATEMENT_PARSER = 'OfxStatementParser',
  CREATE_CATEGORY_USE_CASE = 'CreateCategoryUseCase',
  LIST_CATEGORIES_USE_CASE = 'ListCategoriesUseCase',
  DELETE_CATEGORY_USE_CASE = 'DeleteCategoryUseCase',
  UPDATE_CATEGORY_USE_CASE = 'UpdateCategoryUseCase',
  TRANSACTION_IMPORT_PRODUCER_USE_CASE = 'TransactionImportProducerUseCase',
  TRANSACTION_IMPORT_CONSUMER_USE_CASE = 'TransactionImportConsumerUseCase',
  GET_TRANSACTIONS_BY_DATE_USE_CASE = 'GetTransactionsByDateUseCase',
  UPDATE_TRANSACTION_USE_CASE = 'UpdateTransactionUseCase',
  DASHBOARD_USE_CASE = 'DashboardUseCase',
  TRANSACTION_CONTROLLER = 'TransactionController',
  CATEGORY_CONTROLLER = 'CategoryController',
  DASHBOARD_CONTROLLER = 'DashboardController',
  LOGIN_USE_CASE = 'LoginUseCase',
  SEND_RECOVERY_PASSWORD_TOKEN_USE_CASE = 'SendRecoveryPasswordTokenUseCase',
  CREATE_USER_USE_CASE = 'CreateUserUseCase',
  GET_ME_USE_CASE = 'GetMeUseCase',
  VALIDATE_TOKEN_USE_CASE = 'ValidateTokenUseCase',
  MESSAGE_QUEUE_PORT = 'MessageQueuePort',
  USER_CONTROLLER = 'UserController',
  AUTH_CONTROLLER = 'AuthController',

  // Payments
  PRODUCT_REPOSITORY = 'ProductRepository',
  SUBSCRIPTION_REPOSITORY = 'SubscriptionRepository',
  CREATE_PAYMENT_LINK_USE_CASE = 'CreatePaymentLinkUseCase',
  LIST_PRODUCTS_USE_CASE = 'ListProductsUseCase',
  BILLING_PAID_EVENT_USE_CASE = 'BillingPaidEventUseCase',
  CHECK_SUBSCRIPTION_USE_CASE = 'CheckSubscriptionUseCase',
  PAYMENT_GATEWAY = 'PAYMENT_GATEWAY',
}
